name: PIXID Drive to Sheets Sync

on:
  schedule:
    # Exécution toutes les 15 minutes
    - cron: '*/15 * * * *'
  
  # Permettre l'exécution manuelle
  workflow_dispatch:
    inputs:
      verbose:
        description: 'Activer le mode verbose'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      force_full_sync:
        description: 'Forcer la resynchronisation complète (ignore l\'historique)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

# Permissions pour les actions
permissions:
  contents: read
  issues: write  # Pour créer des issues en cas d'erreur

jobs:
  sync:
    name: Synchronisation PIXID
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: 🔄 Checkout du code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Pour avoir l'historique complet
    
    - name: 🐍 Configuration Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
    
    - name: 📦 Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        # Créer les dossiers nécessaires
        mkdir -p logs
        
    - name: 🔑 Configuration des credentials
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        # Vérifier que les credentials sont présents
        if [ -z "$GOOGLE_CREDENTIALS" ]; then
          echo "❌ GOOGLE_CREDENTIALS secret non configuré!"
          exit 1
        fi
        echo "✅ Credentials Google configurés"
    
    - name: 🗂️ Restauration de l'état précédent
      uses: actions/cache@v4
      with:
        path: |
          sync_state.json
          monitoring_data.json
        key: sync-state-${{ github.sha }}
        restore-keys: |
          sync-state-
    
    - name: 🚀 Exécution de la synchronisation
      id: sync
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        PYTHONUNBUFFERED: '1'  # Pour voir les logs en temps réel
      run: |
        # Définir les options
        VERBOSE_FLAG=""
        if [ "${{ github.event.inputs.verbose }}" = "true" ]; then
          VERBOSE_FLAG="--verbose"
        fi
        
        # Forcer la resync complète si demandé
        if [ "${{ github.event.inputs.force_full_sync }}" = "true" ]; then
          echo "🔄 Suppression de l'état pour forcer la resynchronisation complète"
          rm -f sync_state.json
        fi
        
        # Exécuter le script
        echo "📊 Démarrage de la synchronisation PIXID..."
        python sync_drive_to_sheet.py $VERBOSE_FLAG || EXIT_CODE=$?
        
        # Capturer le code de sortie
        echo "exit_code=${EXIT_CODE:-0}" >> $GITHUB_OUTPUT
        
        # Afficher les statistiques
        if [ -f monitoring_data.json ]; then
          echo "📈 Statistiques de la dernière exécution:"
          python -c "
import json
with open('monitoring_data.json', 'r') as f:
    data = json.load(f)
    if data.get('history'):
        last = data['history'][-1]
        print(f\"  - Fichiers trouvés: {last.get('files_found', 0)}\")
        print(f\"  - Fichiers traités: {last.get('files_processed', 0)}\")
        print(f\"  - Lignes ajoutées: {last.get('rows_added', 0)}\")
        print(f\"  - Durée: {last.get('duration_seconds', 0):.1f}s\")
        print(f\"  - Statut: {last.get('status', 'unknown')}\")
          "
        fi
        
        exit ${EXIT_CODE:-0}
    
    - name: 💾 Sauvegarde des artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sync-artifacts-${{ github.run_number }}
        path: |
          logs/
          sync_state.json
          monitoring_data.json
        retention-days: 7
    
    - name: 📊 Génération du rapport de monitoring
      if: always()
      run: |
        # Créer un rapport markdown
        cat > sync_report.md << 'EOF'
        # 📊 Rapport de Synchronisation PIXID
        
        **Date:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')
        **Run:** #${{ github.run_number }}
        **Déclencheur:** ${{ github.event_name }}
        
        ## Résultats
        EOF
        
        if [ -f monitoring_data.json ]; then
          python -c "
import json
with open('monitoring_data.json', 'r') as f:
    data = json.load(f)
    if data.get('history'):
        last = data['history'][-1]
        
        # Status emoji
        status = last.get('status', 'unknown')
        emoji = '✅' if status == 'success' else '⚠️' if status == 'partial' else '❌'
        
        print(f\"\")
        print(f\"### {emoji} Statut: {status.upper()}\")
        print(f\"\")
        print(f\"| Métrique | Valeur |\")
        print(f\"|----------|--------|\")
        print(f\"| Fichiers trouvés | {last.get('files_found', 0)} |\")
        print(f\"| Fichiers traités | {last.get('files_processed', 0)} |\")
        print(f\"| Fichiers en erreur | {last.get('files_error', 0)} |\")
        print(f\"| Lignes ajoutées | {last.get('rows_added', 0)} |\")
        print(f\"| Durée | {last.get('duration_seconds', 0):.1f}s |\")
        print(f\"\")
        
        # Erreurs
        errors = last.get('errors', [])
        if errors:
            print(f\"### ⚠️ Erreurs rencontrées\")
            print(f\"\")
            for err in errors[:5]:  # Max 5 erreurs
                print(f\"- {err}\")
            if len(errors) > 5:
                print(f\"- ... et {len(errors) - 5} autres erreurs\")
          " >> sync_report.md
        fi
        
        # Afficher le rapport
        cat sync_report.md
    
    - name: 💾 Upload du rapport
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sync-report-${{ github.run_number }}
        path: sync_report.md
        retention-days: 30
    
    - name: 🚨 Création d'issue en cas d'échec
      if: failure() && github.event_name == 'schedule'
      uses: actions/github-script@v7
      with:
        script: |
          const runUrl = `${context.payload.repository.html_url}/actions/runs/${context.runId}`;
          
          // Vérifier s'il y a déjà une issue ouverte
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: ['sync-failure', 'automated']
          });
          
          // Ne pas créer de doublon
          if (issues.data.length > 0) {
            console.log('Une issue est déjà ouverte pour les échecs de sync');
            return;
          }
          
          // Créer une nouvelle issue
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `🚨 Échec de synchronisation PIXID - Run #${context.runNumber}`,
            body: `## Échec de la synchronisation automatique
            
            La synchronisation PIXID a échoué lors de l'exécution planifiée.
            
            **Détails:**
            - 📅 Date: ${new Date().toISOString()}
            - 🔢 Run: #${context.runNumber}
            - 🔗 [Voir les logs](${runUrl})
            
            **Actions suggérées:**
            1. Vérifier les logs de l'exécution
            2. Vérifier la validité des credentials Google
            3. Vérifier l'accès au dossier Drive et au Sheet
            4. Relancer manuellement si nécessaire
            
            cc @${context.actor}`,
            labels: ['sync-failure', 'automated', 'bug']
          });
    
    - name: 📈 Mise à jour du badge de statut
      if: always()
      run: |
        # Créer un fichier pour le badge (peut être utilisé par shields.io)
        mkdir -p .github/badges
        
        STATUS="${{ steps.sync.outputs.exit_code }}"
        if [ "$STATUS" = "0" ]; then
          echo '{"schemaVersion":1,"label":"sync","message":"passing","color":"success"}' > .github/badges/sync.json
        else
          echo '{"schemaVersion":1,"label":"sync","message":"failing","color":"critical"}' > .github/badges/sync.json
        fi
    
    - name: 🧹 Nettoyage des anciennes exécutions
      if: always()
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 7
        keep_minimum_runs: 20
        delete_workflow_pattern: "PIXID Drive to Sheets Sync"
        delete_run_by_conclusion_pattern: "cancelled,skipped"

  notify-success:
    name: Notification de succès
    needs: sync
    if: success() && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
    - name: ✅ Notification de succès
      run: |
        echo "✅ Synchronisation PIXID terminée avec succès!"
        echo "Consultez les artifacts pour plus de détails."
